version: "3.9"
services:
    db:
        container_name: ${NAME}
        image: postgres:14.7-alpine
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
